### ISSUE TITLE
Move Binder Google Cloud project to new org

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/external#20]
https://github.com/jupyterhub/team-compass/issues/427

**Comment by damianavila** [comment]
From the linked issue, it seems there is still a pending decision to adopt the 2i2c google account, is that correct or I am missing additional context?

**Comment by choldgraf** [comment]
Yep, I am not sure which account it'll go to yet. This is just an issue to keep track of that conversation

**Comment by choldgraf** [comment]
this has been completed!
