### ISSUE TITLE
Release nbgitpuller 1.0

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/external#25]
We'd like to release nbgitpuller 1.0, and this issue is to track things that need to happen to make it happen!

# Actions

- [x] #28
- [ ] ~https://github.com/jupyterhub/nbgitpuller/issues/199~ not going to do this because it's more complex than we expected
- [x] Make a release

**Comment by choldgraf** [comment]
I'm adding @consideRatio on this one as he said that he'd be happy to help @GeorgianaElena in doing the work needed to make this release!

**Comment by GeorgianaElena** [comment]
Update: `nbgitpuller` 1.0 has been released, so I'm going to close this issue.

### However
 I didn't do the packaging of the js files correctly and the 1.0 release is broken :( :facepalm: 
 
 Simon is working on fixing it [here](https://github.com/jupyterhub/nbgitpuller/pull/211) (thanks again).

**Comment by choldgraf** [comment]
yay! thanks @GeorgianaElena 🚀
