### ISSUE TITLE
Create content for a blog post for the section "Myst support for roles and directives"

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/external#34]
The idea of this ticket is to track the creation of content and eventually publish a blog post about Myst support for roles and directives.
Check #14 if you need a bigger context.

The proposed outline looks like this (for now, this is evolving content):

# Myst support for roles and directives
## Discuss possible implementations

Steps:

- [x] Create a draft
- [x] Revisit the draft
- [x] Publish and ANN

**Comment by damianavila** [comment]
I am currently at ~50 % on part 2 and it is already complex/heavy for the reader.
We will definitely need a part 3.

**Comment by damianavila** [comment]
Update: I think I will have the draft ready for the first review by today/tomorrow.

**Comment by damianavila** [comment]
This is the draft: https://github.com/damianavila/blog/pull/5

@choldgraf can you please take a look and provide feedback, thanks!!

**Comment by choldgraf** [comment]
done! by the way, I have a PR to support external posts here: https://github.com/2i2c-org/2i2c-org.github.io/pull/63

**Comment by damianavila** [comment]
> by the way, I have a PR to support external posts here: 2i2c-org/2i2c-org.github.io#63

I will take a look soon!

Btw, @choldgraf, I have one more question for you in my blog post proposal.
Appreciated it if you can check it again 😉  .

**Comment by damianavila** [comment]
PR was merged and the blog post published: https://damianavila.github.io/blog/posts/a-deep-dive-into-myst-part-2-the-myst-parser-docutils-and-sphinx.html

Closing here!
