### ISSUE TITLE
Simplify binderhub helm config

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/external#44]
# Summary

Reduce amount of work done in binderhub helm chart, moving it into various other components.

# Links to upstream issues / PRs

- [ ] https://github.com/jupyterhub/binderhub/pull/1351
- [ ] https://github.com/jupyterhub/binderhub/pull/1350

**Comment by choldgraf** [comment]
I guess this one is done? I see lots of merged things!

**Comment by yuvipanda** [comment]
Yep, the second one was just merged! \o/
