### ISSUE TITLE
Split docker-image-cleaner to its own repository from binderhub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/external#47]
# Summary

Splitting [docker-image-cleaner](https://github.com/jupyterhub/binderhub/tree/master/helm-chart/images/image-cleaner) from binderhub into its own repo

# Links to upstream issues / PRs

_A list of links to the upstream issues/PRs where this work is being discussed and developed._

- [x] Use https://github.com/jupyterhub/docker-image-cleaner in binderhub
- [x] https://github.com/jupyterhub/docker-image-cleaner/issues/1

**Comment by choldgraf** [comment]
Do we have an issue open in `binderhub/` for the first task in this issue? I think it'd be best if we had something tracking in BinderHub, so that others in the community know what is coming.

**Comment by yuvipanda** [comment]
This is done!
