### ISSUE TITLE
MIME type error for rise.css

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/external#50]
# Summary

See linked issue for details

# Links to upstream issues / PRs

- [ ] https://github.com/damianavila/RISE/issues/597

**Comment by choldgraf** [comment]
@damianavila you've got this under "needs input" but it's a bit unclear what kind of input you need - can you clarify? :-)

**Comment by rabernat** [comment]
This is not an area where I expect any special treatment related to Pangeo. I opened https://github.com/damianavila/RISE/issues/597 as a regular user of RISE. I doubt it should be a high priority in the context of 2i2c. (Although I would certainly love to fix it eventually!)

**Comment by damianavila** [comment]
> @damianavila you've got this under "needs input" but it's a bit unclear what kind of input you need - can you clarify? :-)

Sorry @choldgraf, I should have been more explicit on this ticket about the "needs input" location, the conversation continued in the referenced RISE issue and I was waiting for Ryan's input at the time I put the card in that column.

**Comment by damianavila** [comment]
Closing this one based on this comment: https://github.com/damianavila/RISE/issues/597#issuecomment-925467238
