### ISSUE TITLE
Write a blog post about our `/test-this-pr` infrastructure

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/external#52]
# Links to upstream issues / PRs

- [x] https://github.com/jupyterhub/team-compass/issues/456

**Comment by sgibson91** [comment]
I am drafting this here: https://hackmd.io/@sgibson91/rJrc5aKEt

**Comment by sgibson91** [comment]
I submitted the hackmd contents to blog.jupyter.org to be reviewed! 🚀

**Comment by sgibson91** [comment]
Just pinged https://github.com/jupyterhub/team-compass/issues/456 again to see if any can review/publish

**Comment by choldgraf** [comment]
posted: https://github.com/jupyterhub/team-compass/issues/456#issuecomment-975809550
